-- CREATE ADMIN USER
DELETE FROM auth.SYS_USER WHERE COD_USERNAME = 'admin';
INSERT INTO auth.SYS_USER (ID_USER,COD_USERNAME, COD_PASSWORD, DSC_USER, FLG_IS_ADMIN)VALUES (1,'admin','admin#123','admin','Y');