-- CREATE ADMIN USER
DELETE FROM auth.SYS_USER WHERE COD_USERNAME = 'admin';
DELETE FROM auth.SYS_USER WHERE COD_USERNAME = 'batch';

INSERT INTO auth.SYS_USER (ID_USER,COD_USERNAME, COD_PASSWORD, DSC_USER, FLG_IS_ADMIN)VALUES (NEXTVAL('user_seq'),'admin','admin#123','admin','Y');
INSERT INTO auth.SYS_USER (ID_USER, COD_USERNAME, COD_PASSWORD, DSC_USER, FLG_IS_ADMIN) VALUES (NEXTVAL('user_seq'), 'batch', 'batch#12', 'batch', 'Y');